object Deps {
    val kotlinVersion = "1.3.20"
    val supportLibraryVersion = "27.1.1"
    val constraintVersion = "1.1.3"
    val roomVersion = "1.1.1"
    val daggerVersion = "2.15"
    val lifecycleVersion = "1.1.1"
    val ktxVersion = "0.3"
    val rxJavaVersion="2.1.14"
    val rxAndroidVersion="2.0.2"
    val junitVersion="4.12"
    val mockitoVersion = "2.18.0"
    val testRunnerVersion="1.0.2"
    val espressoVersion="3.0.2"
    val truthVersion="0.42"
    val mockitoKotlinVersion = "2.0.0"
    val androidJunit5Version="1.3.1.1"
    val spekVersion="2.0.0-rc.1"
    val stethoVersion = "1.5.0"
}
